name: betterminecart
version: '1.6.2-SNAPSHOT'
main: com.duskrainfall.betterminecart.BetterMinecart
api-version: '1.21'
commands:
#  vehiclespeed:
#    description: 获取当前载具速度
#    usage: "/vehiclespeed"
#    #permission:
#    #aliases: vs
  vehicle:
    description: 速度反向/停车
    usage: "/vehicle <back|stop>"
    aliases: ve
permissions:
  spring.create:
    description: 允许玩家创建温泉
    default: op
  spring.remove:
    description: 允许玩家移除温泉
    default: op