name: betterminecart
version: '1.8.1-SNAPSHOT'
main: com.duskrainfall.betterminecart.BetterMinecart
folia-supported: true
api-version: '1.21'
commands:
#  vehiclespeed:
#    description: 获取当前载具速度
#    usage: "/vehiclespeed"
#    #permission:
#    #aliases: vs
  vehicle:
    description: 速度反向/停车/重启
    usage: "/vehicle [back|stop|reset]"
    aliases: ve