name: betterminecart
version: '1.3-SNAPSHOT'
main: com.duskrainfall.betterminecart.BetterMinecart
api-version: '1.21'
commands:
#  vehiclespeed:
#    description: 获取当前载具速度
#    usage: "/vehiclespeed"
#    #permission:
#    #aliases: vs
  vehicleback:
    description: 速度反向
    usage: "/vehicleback"
    aliases: vb
permissions:
  spring.create:
    description: 允许玩家创建温泉。
    default: op
  spring.remove:
    description: 允许玩家移除温泉
    default: op